### ISSUE TITLE
[Suggestions] Couple suggestions that I would personally like to be added.

### ISSUE THREAD

**Issue by BomasJ** [AshKiano/Icarus#1]
I want if possible these things to either be added into a new plugin or this plugin; 
I have been looking for an updated plugin to restrict players who are flying above a certain height in a world, setting them on fire is not enough.

Suggestions:
- Option to teleport players 1-2 blocks down if they get too high. <- If the player is on mount also dismount the player.
- Option to change seconds/ticks between height checks.
- World whitelist option, by default it can include: world, world_nether, world_the_end

**Comment by AshKiano** [comment]
I think, that maybe during today you will find new plugin in my spigot list that will be like that

**Comment by AshKiano** [comment]
https://www.spigotmc.org/resources/flightheightrestrictor-1-16-1-20-1.111711/

**Comment by BomasJ** [comment]
Thank you!

**Comment by BomasJ** [comment]
Seems that with testing, some of the things I recommended do not actually work well, and I wanted to add a reload command. Here are my new suggestions to add to this new plugin (there is no github yet so I am putting them here):

+Change the name to HeightRestrictor because this seems to be more fitting, if you want a different name that is fine
+Add a reload command to reload the config /flightrestrictor reload ?
+Add a true/false **options** for only flight from elytras, mounts or flying (not sure if this is possible); I want players who are placing blocks or walking to not be restricted.
+Let players choose the height per world; not 1 height for all worlds. 
+Add a permission that bypasses this for op players

+Change the system of moving the player down:
  - teleport the player to the current height limit and then specify the amount of blocks under the height limit you want them teleported to; if the player is 300 blocks up, the limit is 200, and the blocks under is 2, it would teleport them to y=198.

If you have any questions or do not want to work on this that is fine, just let me know! (I do not know how to code though)

**Comment by BomasJ** [comment]
I updated the comment a couple times with some ideas.

**Comment by AshKiano** [comment]
Yeah I will soon create github repo for that project and start improving it :)
